### ISSUE TITLE
Cypress Firebase in Github Actions cannot find `CYPRESS_TEST_UID` from secrets.CYPRESS_TEST_UID

### ISSUE THREAD

**Issue by mirshko** [prescottprue/cypress-firebase#1248]
**Describe the bug**

After setting up the `CYPRESS_TEST_UID` secret variable, and setting it in the yaml, the only way the variable is picked up is by hard-coding it in the yaml. 

Constantly getting the following error: `Error: uid must be passed or TEST_UID set within environment to login` 

Additionally, it should be mentioned `SERVICE_ACCOUNT` should be processed to be a string rather than pasting the JSON in directly. fe: `cat serviceAccount.json | jq -c | jq -R`

**To Reproduce**

Here is my GitHub action yaml: 

```yaml
name: Cypress Test

on:
  pull_request:
    branches:
      - main
      - production

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
      - uses: cypress-io/github-action@v6
        with:
          build: pnpm build
          browser: chrome
          start: pnpm preview
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
          CYPRESS_TEST_UID: ${{ secrets.CYPRESS_TEST_UID }}
```

**Expected behavior/code**

The `CYPRESS_TEST_UID` variable when set in secrets should be exposed properly.
