### ISSUE TITLE
Failure to configure and attach custom commands in CI

### ISSUE THREAD

**Issue by lookininward** [prescottprue/cypress-firebase#287]
I have a set of tests that use authentication and read/write to firestore that work 100% in local development.
However, the same setup continues to fail in CI. I can't seem to resolve this error: ` > Your API key is invalid, please check you have copied it correctly.`. I've tried to log the `commands` file but the error occurs before ever hitting them.

I'm pretty sure I'm missing something very obvious but I'm hitting a wall. Any help would be appreciated.

### main.yml workflow
```
e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Cypress Run
        uses: cypress-io/github-action@v2
        with:
          start: yarn run start
          browser: chrome
          headless: true
          wait-on: http://localhost:3000
          wait-on-timeout: 120
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          CYPRESS_TEST_UID: ${{ secrets.TEST_UID }}
          CYPRESS_FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_REF: ${{ github.ref }}
```

### commands.js
![image](https://user-images.githubusercontent.com/14332093/107534107-99cf6a00-6b8d-11eb-8dbf-08427725e069.png)

### secrets
![image](https://user-images.githubusercontent.com/14332093/107535002-5a554d80-6b8e-11eb-892f-100f9ff707bb.png)
