### ISSUE TITLE
ApiKey Error When using Github Actions and Cypress

### ISSUE THREAD

**Issue by isab** [prescottprue/cypress-firebase#370]
**Describe the bug**

I am getting this error when my Cypress test suite runs on Github Actions
```
Your API key is invalid, please check you have copied it correctly.
```

This error only happens in the Github Actions environment and does NOT happen when I run Cypress locally.

**To Reproduce**
It's in a private repo so I can't reproduce it for you specifically. But here is how I run the scripts.

Locally in development: 
`cypress open` to start cypress and run the tests
`yarn dev` to start my localhost:3000 server for the cypress tests

Github Actions Script:
```
name: End-to-end tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn dev
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
          record: true
        env:
          CI_FB_SECRETS: ${{ secrets.CYPRESS_FB_SECRETS }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
          CYPRESS_TEST_UID: ${{ secrets.CYPRESS_UID }}
          SERVICE_ACCOUNT: ${{ secrets.CYPRESS_SERVICE_ACCOUNT }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_REF: ${{ github.ref }}
```
**Expected behavior/code**
The tests should not have the ApiKey error in the Github Actions environment. 

**Additional Context/Screenshots**

Things I've already tried and debugged:
- I have quadruple checked the ApiKeys and they match. I checked all the service account secrets and app secrets from both the Cypress server and my own app server and they all match. 
- `yarn build` and `yarn dev` build the app and start the localhost server without any errors. 
- I've added all the secrets to Github as well and double checked those.

Context:
- I don't run my test suite in a Firebase Emulator. Should I be doing that?

Here's my code:
```
// plugins/index.js
const admin = require('firebase-admin');
const cypressFirebasePlugin = require('cypress-firebase').plugin;

const creds = JSON.parse(process.env.SERVICE_ACCOUNT);

module.exports = (on, config) => {
  admin.initializeApp({
    credential: admin.credential.cert(creds),
    databaseURL: 'https://apollo-sandbox-2f24e.firebaseio.com',
  });
  const extendedConfig = cypressFirebasePlugin(on, config, admin);

  return extendedConfig;
};
```

```
// support/commands.js
import firebase from 'firebase/app';
import 'firebase/auth';
import 'firebase/database';
import 'firebase/firestore';
import { attachCustomCommands } from 'cypress-firebase';

// replaced my secrets with `my app`
const config = {
  apiKey: 'my_key',
  authDomain: 'myapp.firebaseapp.com',
  projectId: 'myapp',
  storageBucket: 'myapp.appspot.com',
  messagingSenderId: '127620730504',
  appId: 'myappId',
  measurementId: 'G-NG3DF18JP4',
};
firebase.initializeApp(config);

attachCustomCommands({ Cypress, cy, firebase });
```

Any help would be appreciated! Happy to provide more context as well.
